"""
Regenerate data/sample_data.sql from the local data/*.csv fixtures, cleaned the same
way the real pipeline does (src/data_pipeline/preprocess.py:Preprocessor), so the seed
data matches what the app actually expects.

data/ itself is gitignored (it's a local/synthetic dataset, not meant to be committed
directly) - this SQL dump is the checked-in, reviewable substitute so anyone can seed a
local Postgres and run the whole platform without needing the original CSVs.

Usage:
    python scripts/generate_sample_data_sql.py > data/sample_data.sql
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.data_pipeline.load_data import DataLoader
from src.data_pipeline.preprocess import Preprocessor
from src.db.models.campaign_log import CampaignLogDB
from src.db.models.customers import CustomerDB
from src.db.models.products import ProductDB
from src.db.models.transactions import TransactionDB


def _sql_literal(value) -> str:
    if pd.isna(value):
        return "NULL"
    if isinstance(value, (int,)):
        return str(value)
    if isinstance(value, float):
        return repr(float(value))
    if isinstance(value, pd.Timestamp):
        return f"'{value.date().isoformat()}'"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def _insert_statements(table: str, columns: list[str], df: pd.DataFrame, batch_size: int = 500) -> list[str]:
    statements = []
    rows = df[columns].values.tolist()
    for i in range(0, len(rows), batch_size):
        batch = rows[i : i + batch_size]
        values = ",\n".join(
            "  (" + ", ".join(_sql_literal(v) for v in row) + ")" for row in batch
        )
        col_list = ", ".join(columns)
        statements.append(
            f"INSERT INTO {table} ({col_list}) VALUES\n{values}\nON CONFLICT DO NOTHING;"
        )
    return statements


def main() -> None:
    loader = DataLoader("data")
    customers = Preprocessor.clean_customer_data(loader.load_customers())
    products = Preprocessor.clean_product_data(loader.load_products())
    transactions = Preprocessor.clean_tx_data(loader.load_transactions())

    # CustomerDB.created_at has no DB-side default (only an ORM-level Python default),
    # so a raw INSERT needs an explicit value or it violates the NOT NULL constraint.
    customers = customers.copy()
    customers["created_at"] = pd.Timestamp("2026-01-01")

    print("-- Auto-generated by scripts/generate_sample_data_sql.py - do not edit by hand.")
    print("-- Self-contained: creates the tables (if missing) then seeds them for a local demo.\n")

    print("-- schema (order matters - customers/products before transactions before campaign_log, FKs)")
    for model in (CustomerDB, ProductDB, TransactionDB, CampaignLogDB):
        ddl = str(CreateTable(model.__table__, if_not_exists=True).compile(dialect=postgresql.dialect()))
        print(ddl.strip() + ";")
    print()

    print("-- customers")
    for stmt in _insert_statements(
        "clean_customers",
        ["customer_id", "email", "name", "age", "gender", "country", "city",
         "phone_number", "interests", "signup_date", "last_purchase_date",
         "total_spent", "purchase_frequency", "churn", "created_at"],
        customers,
    ):
        print(stmt)
    print()

    print("-- products")
    for stmt in _insert_statements(
        "clean_products",
        ["product_id", "product_name", "category", "description", "price", "stock_status"],
        products,
    ):
        print(stmt)
    print()

    print("-- transactions")
    for stmt in _insert_statements(
        "clean_transactions",
        ["transaction_id", "customer_id", "product_id", "total_price", "quantity", "purchase_date"],
        transactions,
    ):
        print(stmt)


if __name__ == "__main__":
    main()
